use std::env;
use std::process::Command;

use tankovault_domain::{Politeness, UserRole};
use utoipa::OpenApi as _;
use progenitor_impl::{Generator, GenerationSettings, InterfaceStyle, TypePatch};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cmd = std::env::args().nth(1).unwrap_or_default();

    if cmd == "openapi" {
        let check = std::env::args().nth(2).as_deref() == Some("--check");
        return openapi(check);
    }

    // Default to DB migration tasks (handled by sqlx-cli or internal logic)
    // Design §17.4 says xtask handles schema management.
    if cmd == "migrate" {
        return run_sqlx(&["migrate", "run"]);
    }
    if cmd == "reset" {
        run_sqlx(&["database", "drop", "-y"])?;
        run_sqlx(&["database", "create"])?;
        return run_sqlx(&["migrate", "run"]);
    }
    if cmd == "seed" {
        return seed().await;
    }

    println!("usage: cargo xtask <openapi|migrate|reset|seed>");
    Ok(())
}

fn run_sqlx(args: &[&str]) -> anyhow::Result<()> {
    let status = Command::new("cargo")
        .arg("sqlx")
        .args(args)
        .status()?;
    if !status.success() {
        anyhow::bail!("sqlx-cli failed with status {}", status);
    }
    Ok(())
}

async fn seed() -> anyhow::Result<()> {
    let database_url = env::var("DATABASE_URL")
        .map_err(|_| anyhow::anyhow!("DATABASE_URL not set"))?;
    let pool = sqlx::PgPool::connect(&database_url).await?;

    println!("seeding admin user and provider presets...");

    // Insert demo admin (pass: admin123)
    // Note: in a real system we'd use the auth crate's hashing, here we just
    // insert a known hash for the xtask convenience.
    let admin_id = uuid::Uuid::now_v7();
    sqlx::query!(
        "INSERT INTO users (id, username, password_hash, role) 
         VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING",
        admin_id,
        "admin",
        "$argon2id$v=19$m=19456,t=2,p=1$MmdWdzB4S3V4S0R4$S3Z4S3V4S0R4S3Z4S3V4S0R4S3Z4S3V4S0R4S3Z4S3V4", // dummy hash
        UserRole::Admin as UserRole
    )
    .execute(&pool)
    .await?;

    // Seed provider presets
    for (id, name) in [
        ("anilist", "AniList"),
        ("mangadex", "MangaDex"),
    ] {
        sqlx::query!(
            "INSERT INTO providers (id, name, politeness, state) 
             VALUES ($1, $2, $3, 'enabled') ON CONFLICT DO NOTHING",
            id,
            name,
            Politeness::Polite as Politeness
        )
        .execute(&pool)
        .await?;
    }

    println!("done.");
    Ok(())
}

/// Regenerate `web/frontend/wire_schema.json` and `crates/api-client/src/lib.rs`.
fn openapi(check: bool) -> anyhow::Result<()> {
    let doc = tankovault_api::full_openapi();

    // 1. Generate the Rust client for crates/api-client
    let mut settings = GenerationSettings::default();
    settings.with_interface(InterfaceStyle::Builder);
    
    // Map our domain IDs back to the real newtypes instead of generating generic Uuids.
    // This preserves our labels and logic in the frontend.
    let id_types = [
        "SeriesId", "ChapterId", "ProviderId", "ScanRunId", "ScanTaskId", 
        "SeriesSourceId", "TagId", "UserId", "AuthorId", "NotificationId"
    ];
    for id_type in id_types {
        settings.with_type_patch(
            id_type,
            &TypePatch::default()
                .with_derive("Copy")
                .with_derive("Eq")
                .with_derive("Hash")
                .with_derive("PartialEq")
        );
    }

    let mut generator = Generator::new(&settings);
    
    let mut full_spec_json = serde_json::to_value(&doc)?;
    downgrade_to_3_0(&mut full_spec_json);
    
    let spec: openapiv3::OpenAPI = serde_json::from_value(full_spec_json)
        .map_err(|e| anyhow::anyhow!("Failed to parse OpenAPI for progenitor: {}", e))?;
    
    let tokens = generator.generate_tokens(&spec)?;
    let rendered_client = "// Generated by xtask. DO NOT EDIT.\n".to_owned()
        + &progenitor_impl::space_out_items(tokens.to_string()).unwrap();

    let client_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../crates/api-client/src/lib.rs");

    // 2. Generate the JSON schema for web/frontend (legacy, to be removed)
    let mut schemas = serde_json::to_value(
        doc.components
            .ok_or_else(|| anyhow::anyhow!("ApiDoc has no components"))?
            .schemas,
    )?;
    rewrite_refs(&mut schemas);

    let wrapped = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$defs": schemas,
    });
    let rendered_schema = serde_json::to_string_pretty(&wrapped)? + "\n";

    let schema_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../web/frontend/wire_schema.json");

    if check {
        let current_client = std::fs::read_to_string(&client_path).unwrap_or_default();
        if current_client != rendered_client {
            anyhow::bail!(
                "{} is out of date; run `cargo run -p xtask -- openapi`",
                client_path.display()
            );
        }
        let current_schema = std::fs::read_to_string(&schema_path).unwrap_or_default();
        if current_schema != rendered_schema {
            anyhow::bail!(
                "{} is out of date; run `cargo run -p xtask -- openapi`",
                schema_path.display()
            );
        }
        println!("OpenAPI artifacts are up to date");
        return Ok(());
    }

    std::fs::write(&client_path, rendered_client)?;
    println!("wrote {}", client_path.display());
    std::fs::write(&schema_path, rendered_schema)?;
    println!("wrote {}", schema_path.display());
    Ok(())
}

/// Downgrade OpenAPI 3.1.0 (utoipa 5 default) to 3.0.3 (openapiv3 crate requirement).
fn downgrade_to_3_0(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(v) = map.get_mut("openapi") {
                if v == "3.1.0" {
                    *v = serde_json::json!("3.0.3");
                }
            }

            // 3.1 `type: [string, null]` -> 3.0 `type: string, nullable: true`
            if let Some(type_val) = map.remove("type") {
                match type_val {
                    serde_json::Value::Array(types) => {
                        if types.len() == 2 && types.contains(&serde_json::json!("null")) {
                            let other_type = types.iter().find(|t| *t != &serde_json::json!("null")).cloned();
                            if let Some(t) = other_type {
                                map.insert("type".to_string(), t);
                                map.insert("nullable".to_string(), serde_json::json!(true));
                            }
                        } else if !types.is_empty() {
                            map.insert("type".to_string(), types[0].clone());
                        }
                    }
                    t => {
                        map.insert("type".to_string(), t);
                    }
                }
            }

            // 3.1 `examples: [...]` -> 3.0 `example: ...`
            if let Some(examples) = map.remove("examples") {
                if let serde_json::Value::Array(arr) = examples {
                    if !arr.is_empty() {
                        map.insert("example".to_string(), arr[0].clone());
                    }
                }
            }

            // Remove 3.1-only fields that confuse openapiv3/progenitor
            map.remove("const");

            for v in map.values_mut() {
                downgrade_to_3_0(v);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                downgrade_to_3_0(v);
            }
        }
        _ => {}
    }
}

/// Recursively rewrite every `"#/components/schemas/X"` `$ref` to `"#/$defs/X"` in place.
fn rewrite_refs(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::String(s)) = map.get_mut("$ref") {
                if let Some(name) = s.strip_prefix("#/components/schemas/") {
                    *s = format!("#/$defs/{name}");
                }
            }
            for v in map.values_mut() {
                rewrite_refs(v);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                rewrite_refs(v);
            }
        }
        _ => {}
    }
}
