//! Developer/ops tasks.
//!
//! - `xtask migrate` — apply all pending migrations (used as the deploy migration step).
//! - `xtask reset`   — drop & recreate the `public` schema, then re-migrate (DESTRUCTIVE,
//!   local dev only; guarded by `TANKOVAULT_CONFIRM_RESET=1`).
//! - `xtask seed`    — insert a demo admin user and the built-in provider presets.
//! - `xtask openapi` — regenerate `web/frontend/wire_schema.json` from the api service's
//!   `utoipa` schemas (the frontend's `typify` codegen input). No database needed.
//!
//! `migrate`/`reset`/`seed` read `DATABASE_URL` from the environment; `openapi` does not.

use progenitor_impl::{GenerationSettings, Generator, InterfaceStyle, TypePatch};
use tankovault_domain::{Politeness, UserRole};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cmd = std::env::args().nth(1).unwrap_or_default();

    if cmd == "openapi" {
        let check = std::env::args().nth(2).as_deref() == Some("--check");
        return openapi(check);
    }

    let url =
        std::env::var("DATABASE_URL").map_err(|_| anyhow::anyhow!("DATABASE_URL must be set"))?;
    let pool = tankovault_db::connect(&url, 5, 10).await?;

    match cmd.as_str() {
        "migrate" => {
            tankovault_db::migrate(&pool).await?;
            println!("migrations applied");
        }
        "reset" => reset(&pool).await?,
        "seed" => seed(&pool).await?,
        other => {
            eprintln!(
                "unknown command {other:?}; usage: xtask <migrate|reset|seed|openapi [--check]>"
            );
            std::process::exit(2);
        }
    }
    Ok(())
}

/// Dump the api service's `utoipa` component schemas as a plain JSON Schema document (no
/// `OpenAPI` envelope — just `$defs`), so `typify` can consume it directly on the frontend
/// side. `#/components/schemas/X` refs (`OpenAPI` convention) are rewritten to `#/$defs/X`
/// (JSON Schema 2020-12 convention, what `typify` resolves).
///
/// With `check = true`, nothing is written: the freshly generated document is compared
/// against the file on disk and the command exits non-zero if they differ. Used by CI
/// (`.github/workflows/ci.yml`) and the pre-commit hook (`hooks/pre-commit`) instead of a
/// generate-then-`git diff` dance.
fn openapi(check: bool) -> anyhow::Result<()> {
    let doc = tankovault_api::full_openapi();

    let full_spec_json = serde_json::to_value(&doc)?;
    let spec_path = "openapi.json";
    std::fs::write(spec_path, serde_json::to_string_pretty(&full_spec_json)?)?;

    // 1. Generate the Rust client for crates/api-client
    let mut settings = GenerationSettings::default();
    settings.with_interface(InterfaceStyle::Builder);
    // Every generated type crosses a Dioxus component boundary on the frontend (props,
    // signals, memos), all of which require `PartialEq`. progenitor only derives it when
    // asked, so add it globally here.
    settings.with_derive("PartialEq");

    // Map our domain IDs back to the real newtypes instead of generating generic Uuids.
    // This preserves our labels and logic in the frontend.
    let id_types = [
        "SeriesId",
        "ChapterId",
        "ProviderId",
        "ScanRunId",
        "ScanTaskId",
        "SeriesSourceId",
        "TagId",
        "UserId",
        "AuthorId",
        "NotificationId",
    ];
    for id_type in id_types {
        settings.with_patch(
            id_type,
            TypePatch::default()
                .with_derive("Copy")
                .with_derive("Eq")
                .with_derive("Hash")
                .with_derive("PartialEq"),
        );
    }

    let mut generator = Generator::new(&settings);

    let mut full_spec_json = serde_json::to_value(&doc)?;
    downgrade_to_3_0(&mut full_spec_json);
    inject_rust_types(&mut full_spec_json);

    let spec: openapiv3::OpenAPI = serde_json::from_value(full_spec_json)
        .map_err(|e| anyhow::anyhow!("Failed to parse OpenAPI for progenitor: {e}"))?;

    let tokens = generator.generate_tokens(&spec)?;
    let rendered_client = "// Generated by xtask. DO NOT EDIT.\n".to_owned()
        + &progenitor_impl::space_out_items(tokens.to_string()).unwrap();

    let client_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../crates/api-client/src/lib.rs");

    // 2. Generate the JSON schema for web/frontend (legacy, to be removed)
    let mut schemas = serde_json::to_value(
        doc.components
            .ok_or_else(|| anyhow::anyhow!("ApiDoc has no components"))?
            .schemas,
    )?;
    rewrite_refs(&mut schemas);

    let wrapped = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$defs": schemas,
    });
    let rendered_schema = serde_json::to_string_pretty(&wrapped)? + "\n";

    let schema_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../web/frontend/wire_schema.json");

    if check {
        let current_client = std::fs::read_to_string(&client_path).unwrap_or_default();
        if current_client != rendered_client {
            anyhow::bail!(
                "{} is out of date; run `cargo run -p xtask -- openapi`",
                client_path.display()
            );
        }
        let current_schema = std::fs::read_to_string(&schema_path).unwrap_or_default();
        if current_schema != rendered_schema {
            anyhow::bail!(
                "{} is out of date; run `cargo run -p xtask -- openapi`",
                schema_path.display()
            );
        }
        println!("OpenAPI artifacts are up to date");
        return Ok(());
    }

    std::fs::write(&client_path, rendered_client)?;
    println!("wrote {}", client_path.display());
    std::fs::write(&schema_path, rendered_schema)?;
    println!("wrote {}", schema_path.display());
    Ok(())
}

/// Inject `x-rust-type` into specific schema components to use our domain newtypes.
fn inject_rust_types(value: &mut serde_json::Value) {
    if let Some(schemas) = value.pointer_mut("/components/schemas") {
        if let Some(map) = schemas.as_object_mut() {
            let id_types = [
                ("SeriesId", "tankovault_domain::SeriesId"),
                ("ChapterId", "tankovault_domain::ChapterId"),
                ("ProviderId", "tankovault_domain::ProviderId"),
                ("ScanRunId", "tankovault_domain::ScanRunId"),
                ("ScanTaskId", "tankovault_domain::ScanTaskId"),
                ("SeriesSourceId", "tankovault_domain::SeriesSourceId"),
                ("TagId", "tankovault_domain::TagId"),
                ("UserId", "tankovault_domain::UserId"),
                ("AuthorId", "tankovault_domain::AuthorId"),
                ("NotificationId", "tankovault_domain::NotificationId"),
                // Enums too
                ("ContentType", "tankovault_domain::ContentType"),
                ("SeriesStatus", "tankovault_domain::SeriesStatus"),
                ("WatchStatus", "tankovault_domain::WatchStatus"),
                ("RunState", "tankovault_domain::RunState"),
                ("ScanMode", "tankovault_domain::ScanMode"),
                ("Politeness", "tankovault_domain::Politeness"),
                ("UserRole", "tankovault_domain::UserRole"),
            ];

            for (name, rust_type) in id_types {
                if let Some(schema) = map.get_mut(name) {
                    if let Some(s_map) = schema.as_object_mut() {
                        s_map.insert("x-rust-type".to_string(), serde_json::json!(rust_type));
                    }
                }
            }
        }
    }
}

/// Downgrade `OpenAPI` 3.1.0 (utoipa 5 default) to 3.0.3 (openapiv3 crate requirement).
/// This handles the `type: [string, null]` -> `type: string, nullable: true` conversion
/// and changes the version string.
fn downgrade_to_3_0(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(v) = map.get_mut("openapi") {
                if v == "3.1.0" {
                    *v = serde_json::json!("3.0.3");
                }
            }

            // Handle 'type' which can be a string or an array in 3.1
            if let Some(type_val) = map.remove("type") {
                match type_val {
                    serde_json::Value::String(s) => {
                        if s == "null" {
                            map.insert("nullable".to_string(), serde_json::json!(true));
                        } else {
                            map.insert("type".to_string(), serde_json::Value::String(s));
                        }
                    }
                    serde_json::Value::Array(types) => {
                        if types.len() == 2 && types.contains(&serde_json::json!("null")) {
                            let other_type = types
                                .iter()
                                .find(|t| *t != &serde_json::json!("null"))
                                .cloned();
                            if let Some(t) = other_type {
                                map.insert("type".to_string(), t);
                                map.insert("nullable".to_string(), serde_json::json!(true));
                            }
                        } else if !types.is_empty() {
                            // Pick the first non-null type if possible
                            let first_type = types
                                .iter()
                                .find(|t| *t != &serde_json::json!("null"))
                                .or_else(|| types.first());
                            if let Some(t) = first_type {
                                if t == "null" {
                                    map.insert("nullable".to_string(), serde_json::json!(true));
                                } else {
                                    map.insert("type".to_string(), t.clone());
                                }
                            }
                        }
                    }
                    _ => {}
                }
            }

            // Also handle 'examples' -> 'example' (OpenAPI 3.0 vs 3.1)
            if let Some(serde_json::Value::Array(arr)) = map.remove("examples") {
                if !arr.is_empty() {
                    map.insert("example".to_string(), arr[0].clone());
                }
            }

            for v in map.values_mut() {
                downgrade_to_3_0(v);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                downgrade_to_3_0(v);
            }
        }
        _ => {}
    }
}

/// Recursively rewrite every `"#/components/schemas/X"` `$ref` to `"#/$defs/X"` in place.
fn rewrite_refs(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::String(s)) = map.get_mut("$ref") {
                if let Some(name) = s.strip_prefix("#/components/schemas/") {
                    *s = format!("#/$defs/{name}");
                }
            }
            for v in map.values_mut() {
                rewrite_refs(v);
            }
        }
        serde_json::Value::Array(items) => {
            for v in items {
                rewrite_refs(v);
            }
        }
        _ => {}
    }
}

/// Drop the whole schema and re-migrate from scratch. Refuses to run unless
/// `TANKOVAULT_CONFIRM_RESET=1` is set, so it cannot wipe a database by accident
/// (e.g. a mis-pointed `DATABASE_URL` in a shell that also targets staging).
async fn reset(pool: &tankovault_db::PgPool) -> anyhow::Result<()> {
    if std::env::var("TANKOVAULT_CONFIRM_RESET").as_deref() != Ok("1") {
        anyhow::bail!(
            "refusing to reset: this DROPs the public schema and destroys all data. \
             Re-run with TANKOVAULT_CONFIRM_RESET=1 to confirm."
        );
    }
    tankovault_db::reset(pool).await?;
    println!("database reset: schema dropped and migrations re-applied");
    Ok(())
}

async fn seed(pool: &tankovault_db::PgPool) -> anyhow::Result<()> {
    // Admin user (idempotent: ignore if already present).
    let password = std::env::var("TANKOVAULT_SEED_ADMIN_PASSWORD")
        .unwrap_or_else(|_| "changeme12345".to_owned());
    let hash = tankovault_auth::hash_password(&password)
        .map_err(|e| anyhow::anyhow!("hash failed: {e}"))?;
    match tankovault_db::repo::users::create(
        pool,
        "admin@tankovault.local",
        "admin",
        &hash,
        UserRole::Admin,
    )
    .await
    {
        Ok(u) => println!("seeded admin user {} (password: {password})", u.username),
        Err(e) if e.is_unique_violation() || matches!(e, tankovault_db::DbError::Conflict(_)) => {
            println!("admin user already present; skipping");
        }
        Err(e) => return Err(e.into()),
    }

    // Built-in provider presets (design §7): the custom demonicscans adapter plus the
    // Madara-configured manhuaus and kunmanga. Operators are responsible for the legality
    // of crawling; disable or retarget any provider via the admin console.
    for preset in tankovault_adapters::builtin_presets() {
        match tankovault_db::repo::providers::create(
            pool,
            tankovault_db::repo::providers::NewProvider {
                slug: preset.slug.to_owned(),
                name: preset.name.to_owned(),
                base_url: preset.base_url.to_owned(),
                adapter: preset.adapter,
                config: preset.config,
                politeness: Politeness::default(),
            },
        )
        .await
        {
            Ok(p) => println!("seeded provider '{}' ({})", p.slug, p.id),
            Err(tankovault_db::DbError::Conflict(_)) => {
                println!("provider '{}' already present; skipping", preset.slug);
            }
            Err(e) => return Err(e.into()),
        }
    }

    Ok(())
}
