//! Query-plan regression tests for the trigram search paths (`repo::matching`,
//! `repo::sync::admin_views`, `repo::catalog::browse`).
//!
//! # The bug these exist to stop
//!
//! Every one of these queries used to read `s.normalized_title % $1 OR EXISTS (SELECT 1 FROM
//! series_titles st WHERE … st.normalized % $1)`. **An `EXISTS` under `OR` cannot be pulled up
//! into a semi-join**, and the consequence is not a slightly worse plan: Postgres cannot use
//! *any* index on `series` for such a predicate, so it sequentially scans the whole table and
//! evaluates `similarity()` per row. On the production catalogue that was 54 551 rows and
//! 425–1 251 ms per call, with a cost estimate high enough to trigger a further ~260 ms of
//! pointless JIT compilation. The trigram GIN indexes existed the entire time and were simply
//! unreachable, which is why nothing in the schema looked wrong and why no correctness test
//! could have caught it.
//!
//! # Why these assert on plans and never on time
//!
//! A wall-clock threshold on a shared CI runner is either so loose it would have passed the
//! 1 251 ms query or so tight it flakes. The plan is the actual invariant, and it is
//! deterministic: the fixture is generated from a fixed seed, `ANALYZE`d once in the template,
//! and cloned per test.
//!
//! Two things make the assertions meaningful, and both are easy to break from a distance:
//!
//! - **The SQL is read out of the committed `.sqlx` cache, not copied into this file.** That
//!   cache is what `sqlx::query!` compiled, regenerated by `cargo run -p xtask -- sqlx-prepare`,
//!   so the statement asserted on here is provably the statement the repository runs. A copy
//!   would drift, and a plan test that passes against a query nobody executes is worse than
//!   none.
//! - **The fixture has to be big enough** — see `TestDb::spawn_with_catalogue`. Below the
//!   crossover a sequential scan is the *correct* plan, so there would be nothing to assert.
//!   That case fails rather than passes — `assert_index_driven` requires the indexes to be
//!   *used*, which a too-small fixture cannot satisfy — which is the safe direction, but the
//!   failure would be confusing, hence this note.
//!
//! # Two tests, two lenses
//!
//! `every_query_plan_passes_the_audit` sweeps **every** statement in the offline cache under
//! `EXPLAIN (GENERIC_PLAN)`, which needs no parameter values and so scales to all of them, and
//! applies the rules in [`audit`] to each. `trigram_searches_reach_their_indexes` binds real
//! values for the four the slow-statement log named and asserts the sharper property that the
//! specific indexes are used. The sweep finds the bug class anywhere it appears, and anything
//! else expensive; the targeted test pins the fix that was made.
//!
//! Opt-in: gated behind the `integration` feature because it requires Docker.
#![cfg(feature = "integration")]

use std::path::PathBuf;

use serde_json::Value;
use sqlx::{PgPool, Row as _};
use tankovault_test_support::TestDb;

/// One `sqlx::query!` invocation as the offline cache recorded it.
struct CachedQuery {
    sql: String,
    columns: Vec<String>,
    params: Vec<String>,
}

/// Every query in the committed `.sqlx` cache.
fn cached_queries() -> Vec<CachedQuery> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../.sqlx");
    let entries = std::fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("read the sqlx cache at {}: {err}", dir.display()));

    let mut queries = Vec::new();
    for entry in entries {
        let path = entry.expect("read a sqlx cache entry").path();
        if path.extension().is_none_or(|ext| ext != "json") {
            continue;
        }
        let raw = std::fs::read_to_string(&path).expect("read a sqlx cache file");
        let doc: Value = serde_json::from_str(&raw).expect("parse a sqlx cache file");
        let describe = &doc["describe"];
        queries.push(CachedQuery {
            sql: doc["query"]
                .as_str()
                .expect("cache entry has a query")
                .into(),
            columns: describe["columns"]
                .as_array()
                .expect("cache entry has columns")
                .iter()
                .map(|c| c["name"].as_str().unwrap_or_default().to_owned())
                .collect(),
            params: describe["parameters"]["Left"]
                .as_array()
                .map(|ps| {
                    ps.iter()
                        .map(|p| p.as_str().unwrap_or("Custom").to_owned())
                        .collect()
                })
                .unwrap_or_default(),
        });
    }
    assert!(!queries.is_empty(), "the sqlx cache is empty");
    queries
}

/// The one cached query matching `pred`.
///
/// Insisting on *exactly* one is the point: the predicates below identify a query by the columns
/// it returns rather than by its text, so they survive a rewrite of the query — but a second
/// match would mean the key had become ambiguous and the suite was no longer asserting on what
/// it names. Both zero and many fail loudly rather than picking one.
fn find<'q>(
    queries: &'q [CachedQuery],
    label: &str,
    pred: impl Fn(&CachedQuery) -> bool,
) -> &'q CachedQuery {
    let mut hits = queries.iter().filter(|q| pred(q));
    let hit = hits
        .next()
        .unwrap_or_else(|| panic!("no cached query matches {label}; has it been rewritten?"));
    assert!(
        hits.next().is_none(),
        "{label} matches more than one cached query; the key is ambiguous"
    );
    hit
}

fn has_column(q: &CachedQuery, name: &str) -> bool {
    q.columns.iter().any(|c| c == name)
}

/// `EXPLAIN` the cached statement, binding a title the fixture actually contains.
///
/// A title drawn from the fixture rather than a literal matters: `%` against a value with no
/// trigrams in common with anything would let the planner reason from an empty result.
async fn plan_of(pool: &PgPool, query: &CachedQuery) -> Value {
    let probe: String = sqlx::query_scalar("SELECT normalized_title FROM series LIMIT 1")
        .fetch_one(pool)
        .await
        .expect("read a probe title from the catalogue fixture");

    // The statement is the committed cache's own text — what `sqlx::query!` compiled — with a
    // fixed prefix. There is no caller input anywhere in it.
    let sql = sqlx::AssertSqlSafe(format!("EXPLAIN (FORMAT JSON) {}", query.sql));
    let mut explain = sqlx::query_scalar::<_, Value>(sql);
    for param in &query.params {
        explain = match param.as_str() {
            "Text" => explain.bind(probe.clone()),
            "TextArray" => explain.bind(vec![probe.clone()]),
            "Int8" => explain.bind(10_i64),
            other => panic!("no probe value for parameter type {other}"),
        };
    }
    explain
        .fetch_one(pool)
        .await
        .expect("EXPLAIN the cached statement")
}

/// `EXPLAIN` the cached statement without binding anything, using `GENERIC_PLAN`.
///
/// This is what makes a sweep over *every* cached query possible: `GENERIC_PLAN` (Postgres 16+)
/// plans a parameterised statement with no values at all, so the sweep needs no synthesised
/// `uuid`, enum, timestamp or array for the couple of hundred statements it does not otherwise
/// know anything about. It is also the pessimistic lens — no parameter is a known constant, so
/// the planner cannot fold a predicate away — which is the right default for "this operator must
/// never be evaluated row by row" and the wrong one for anything that depends on a value, hence
/// [`KNOWN_UNINDEXED`].
/// It goes over the **simple** query protocol deliberately. `sqlx::query*` uses the extended one,
/// which prepares the statement — and a prepared `EXPLAIN (GENERIC_PLAN) … $1 …` still declares
/// the placeholders, so the server demands binds for the very parameters `GENERIC_PLAN` exists to
/// do without ("bind message supplies 0 parameters, but prepared statement requires 4").
/// `raw_sql` sends the text as-is, which is what psql does and what makes this work.
async fn generic_plan_of(pool: &PgPool, query: &CachedQuery) -> Value {
    // The committed cache's own text with a fixed prefix; no caller input anywhere in it.
    let sql = sqlx::AssertSqlSafe(format!("EXPLAIN (GENERIC_PLAN, FORMAT JSON) {}", query.sql));
    let row = sqlx::raw_sql(sql)
        .fetch_one(pool)
        .await
        .expect("EXPLAIN (GENERIC_PLAN) the cached statement");
    // The simple protocol returns everything in text format, so the `json` column is read as the
    // string it arrives as and parsed here rather than decoded by sqlx.
    let raw: String = row
        .try_get_unchecked(0)
        .expect("read the plan document from the EXPLAIN row");
    serde_json::from_str(&raw).expect("parse the plan document")
}

/// Visit every node of an `EXPLAIN (FORMAT JSON)` document, subplans included.
fn walk(node: &Value, visit: &mut impl FnMut(&Value)) {
    visit(node);
    if let Some(children) = node.get("Plans").and_then(Value::as_array) {
        for child in children {
            walk(child, visit);
        }
    }
}

/// Assert the trigram predicates are answered by the trigram indexes.
///
/// # Why this is not "the plan contains no sequential scan"
///
/// That was the first version of this assertion and it is wrong. A plan may legitimately reach
/// `series` by scanning it — joining the matched ids back to the table is a hash join against a
/// full scan at fixture scale and a per-row index lookup at production scale, and *both* are
/// correct; the planner is choosing on cost, and it is right either way. Forbidding the scan
/// outright fails the good plan for the wrong reason and teaches the next person to delete the
/// test.
///
/// What the bug actually looks like is narrower, and is what these two assertions pin:
///
/// - the `%` operator evaluated as a **filter on a sequential scan**, which is what "the index
///   is unusable, so look at every row" renders as; and
/// - `series_title_trgm` **missing from the plan entirely**. Under the `OR` form the planner
///   still reaches `series_titles_trgm` through the hashed subquery, so asserting merely that
///   *some* trigram index is used would have passed the bug. Both indexes must appear.
fn assert_index_driven(plan: &Value, label: &str) {
    let mut scans_filtering_on_similarity: Vec<String> = Vec::new();
    let mut trigram_indexes: Vec<String> = Vec::new();

    walk(&plan[0]["Plan"], &mut |node| {
        let node_type = node["Node Type"].as_str().unwrap_or_default();
        let filter = node["Filter"].as_str().unwrap_or_default();
        // ` % ` is how EXPLAIN renders `pg_trgm`'s similarity operator. On a bitmap heap scan it
        // appears as a `Recheck Cond`, which is the index doing its job; on a *sequential* scan
        // it is the whole table being compared row by row.
        if node_type == "Seq Scan" && filter.contains(" % ") {
            let relation = node["Relation Name"].as_str().unwrap_or_default();
            scans_filtering_on_similarity.push(relation.to_owned());
        }
        if let Some(index) = node["Index Name"].as_str()
            && index.contains("trgm")
        {
            trigram_indexes.push(index.to_owned());
        }
    });

    let pretty = serde_json::to_string_pretty(plan).unwrap_or_default();
    assert!(
        scans_filtering_on_similarity.is_empty(),
        "{label} evaluates the trigram operator as a filter while sequentially scanning \
         {scans_filtering_on_similarity:?}. An `EXISTS` under `OR` is the usual cause: it cannot \
         become a semi-join, so no index on the table is usable. Plan:\n{pretty}"
    );
    for required in ["series_title_trgm", "series_titles_trgm"] {
        assert!(
            trigram_indexes.iter().any(|used| used == required),
            "{label} does not use {required}; it reached only {trigram_indexes:?}. Plan:\n{pretty}"
        );
    }
}

/// Whether any node in the plan evaluates the trigram operator as a row filter.
///
/// `Filter` is the field that matters, and the node type does not: the pathology is "compare
/// every row the scan produced", and a scan that produces every row is as easily an ordered
/// `Index Scan` as a `Seq Scan` — one of the three queries below reaches it through
/// `series_updated_idx`, at an estimated cost of 1.9 million. A `Recheck Cond` on a bitmap heap
/// scan carries the same operator and is *not* a violation: that is the index having already
/// narrowed the rows and Postgres confirming them.
fn filters_on_similarity(plan: &Value) -> Option<String> {
    let mut found = None;
    walk(&plan[0]["Plan"], &mut |node| {
        if found.is_some() {
            return;
        }
        if let Some(filter) = node["Filter"].as_str()
            && filter.contains(" % ")
        {
            found = Some(filter.to_owned());
        }
    });
    found
}

/// The estimated total cost above which a query is treated as a finding.
///
/// Not an invented number: 100 000 is Postgres's own `jit_above_cost` default — the point at
/// which it judges a query expensive enough that compiling machine code for it will pay for
/// itself. The original bug estimated 1.95M and did trigger that JIT, wasting ~260 ms per call
/// on top of the scan.
///
/// It detects pathologies, not budgets. The fixture is production divided by roughly six
/// ([`workload`-scale row counts][crate-fixture]), so a query at the ceiling here is worse than
/// the ceiling suggests, and the threshold is deliberately lenient rather than a per-query
/// target.
///
/// [crate-fixture]: TestDb::spawn_with_catalogue
const COST_CEILING: f64 = 100_000.0;

/// A query that breaches a rule, with the cost it is not allowed to exceed.
///
/// This is a debt list, not a suppression. Every entry must still match something (a fixed query
/// whose entry was not deleted fails the audit) and every entry caps the cost it was admitted at,
/// so a budgeted query that gets *worse* fails too. Entries are removed, never raised.
///
/// **The ceilings carry roughly 2x headroom deliberately.** A cost estimate is a function of the
/// statistics, and the fixture is `ANALYZE`d afresh every time a container builds its template,
/// so the same query does not estimate identically forever — `default_statistics_target` is
/// raised to make every table but `chapters` sample whole, which removes most of that drift but
/// not all of it. Tightening these to the last observed figure would buy sensitivity the
/// measurement cannot support and produce failures nobody caused. They catch a query becoming
/// *categorically* worse, not a 10% drift.
struct Budget {
    label: &'static str,
    matches: fn(&CachedQuery) -> bool,
    ceiling: f64,
    reason: &'static str,
}

const BUDGETS: &[Budget] = &[
    Budget {
        label: "browse::list_series/count_series, optional-search variants",
        matches: |query| {
            query.sql.contains("$1::text IS NULL") && query.sql.contains("plainto_tsquery")
        },
        ceiling: 2_000_000.0,
        reason: "still the `OR EXISTS` form. Their search term is optional — the predicate is \
                 guarded by `$1::text IS NULL OR …`, because one statement serves a filtered \
                 browse with no search box — so a UNION of index scans cannot be substituted \
                 unconditionally: with no term there is nothing to union. Needs two statements \
                 or a different rewrite.",
    },
    Budget {
        label: "tracking::dashboard recommendations",
        matches: |query| query.sql.contains("liked_tags"),
        ceiling: 700_000.0,
        reason: "scores every series against the reader's tags, and computes the same correlated \
                 `count(*) … IN (SELECT tag_id FROM liked_tags)` twice — once in the `WHERE \
                 EXISTS`, once in the `ORDER BY` — before the LIMIT. Found by this audit rather \
                 than by a slow-statement log.",
    },
];

/// The budget covering `query`, if any.
fn budget_for(query: &CachedQuery) -> Option<&'static Budget> {
    BUDGETS.iter().find(|budget| (budget.matches)(query))
}

/// One rule breach.
struct Finding {
    rule: &'static str,
    detail: String,
}

/// Apply every rule to one plan.
///
/// The two rules catch different things and neither subsumes the other: the cost ceiling would
/// not have flagged `admin_views::suggest_series_candidates` (455 ms, but only ~4 000 estimated
/// on this fixture), and the trigram rule cannot see a query that is expensive for any other
/// reason — which is how the dashboard recommendation query above was found.
fn audit(plan: &Value) -> Vec<Finding> {
    let mut findings = Vec::new();

    if let Some(filter) = filters_on_similarity(plan) {
        findings.push(Finding {
            rule: "trigram-match-as-filter",
            detail: format!(
                "evaluates the trigram operator row by row. An `EXISTS` under `OR` is the usual \
                 cause: it cannot become a semi-join, so no index on the table is usable. \
                 Filter: {filter}"
            ),
        });
    }

    let cost = total_cost(plan);
    if cost > COST_CEILING {
        findings.push(Finding {
            rule: "estimated-cost-ceiling",
            detail: format!("estimated total cost {cost:.0}, ceiling {COST_CEILING:.0}"),
        });
    }

    findings
}

/// The planner's estimated total cost for the whole statement.
fn total_cost(plan: &Value) -> f64 {
    plan[0]["Plan"]["Total Cost"].as_f64().unwrap_or_default()
}

/// **Every query in the workspace, held to the plan rules.**
///
/// The sweep is the point. The queries the targeted test names are the ones found by reading a
/// slow-statement log, and reading logs is not a way to find the other two hundred — nor a way to
/// find anything before it ships. This explains every statement in the offline cache, which is
/// every `sqlx::query!` in the workspace, and reports each rule breach against its budget.
#[tokio::test]
async fn every_query_plan_passes_the_audit() {
    let db = TestDb::spawn_with_catalogue().await;
    let queries = cached_queries();

    let mut plans: Vec<(&CachedQuery, f64, Vec<Finding>)> = Vec::new();
    for query in &queries {
        let plan = generic_plan_of(&db.pool, query).await;
        plans.push((query, total_cost(&plan), audit(&plan)));
    }

    // Always printed, so a failing run identifies the shape of the workload and not just the one
    // query that tipped over. Visible with `--nocapture`, and on any failure.
    plans.sort_by(|a, b| b.1.total_cmp(&a.1));
    eprintln!("\n-- most expensive plans on the workload fixture");
    for (query, cost, _) in plans.iter().take(10) {
        eprintln!("  {cost:>12.0}  {}", one_line(&query.sql, 100));
    }

    let mut unbudgeted = Vec::new();
    let mut used: Vec<&str> = Vec::new();
    for (query, _, findings) in &plans {
        if findings.is_empty() {
            continue;
        }
        match budget_for(query) {
            Some(budget) => used.push(budget.label),
            None => unbudgeted.push((query, findings)),
        }
    }

    for (query, findings) in &unbudgeted {
        eprintln!("\n-- unbudgeted: {}", one_line(&query.sql, 400));
        for finding in *findings {
            eprintln!("   [{}] {}", finding.rule, finding.detail);
        }
    }
    assert!(
        unbudgeted.is_empty(),
        "{} quer{} breach a plan rule with no budget (printed above). Fix it, or add a `Budget` \
         saying why it is acceptable and what it may not exceed.",
        unbudgeted.len(),
        if unbudgeted.len() == 1 { "y" } else { "ies" }
    );

    // A budgeted query that got *worse* is the regression this audit exists to catch.
    for (query, cost, _) in &plans {
        let Some(budget) = budget_for(query) else {
            continue;
        };
        assert!(
            *cost <= budget.ceiling,
            "budget \"{}\" is exceeded: estimated cost {cost:.0} > {:.0}. Budgets are lowered, \
             never raised.\n  {}",
            budget.label,
            budget.ceiling,
            budget.reason
        );
    }
    for budget in BUDGETS {
        assert!(
            used.contains(&budget.label),
            "budget \"{}\" matches nothing that breaches a rule — delete it",
            budget.label
        );
    }
}

/// A statement collapsed onto one line and truncated, for a readable report.
fn one_line(sql: &str, limit: usize) -> String {
    let flat = sql.split_whitespace().collect::<Vec<_>>().join(" ");
    if flat.len() <= limit {
        return flat;
    }
    format!("{}…", &flat[..limit])
}

/// The four trigram searches must all reach `series` through the GIN indexes.
///
/// One test rather than four: the fixture clone dominates the runtime, and the four assertions
/// share it. A failure names the query.
#[tokio::test]
async fn trigram_searches_reach_their_indexes() {
    let db = TestDb::spawn_with_catalogue().await;
    let queries = cached_queries();

    // Identified by returned columns, so a rewrite of the SQL does not silently unhook the test.
    // `repo::matching::find_candidates` — the query the slow-statement log named.
    // `alt_titles!` as well as `sim!`: the duplicate sweep's `pair_similarities` also returns a
    // `sim!`, and it is a different query with a legitimately different plan.
    let find_candidates = find(&queries, "matching::find_candidates", |q| {
        has_column(q, "sim!") && has_column(q, "alt_titles!") && !has_column(q, "query_title!")
    });
    // `repo::matching::find_candidates_multi` — the only one taking a title array.
    let find_candidates_multi = find(&queries, "matching::find_candidates_multi", |q| {
        has_column(q, "query_title!")
    });
    // `repo::sync::admin_views::suggest_series_candidates`.
    let suggest_candidates = find(&queries, "admin_views::suggest_series_candidates", |q| {
        has_column(q, "similarity!")
    });
    // `repo::catalog::browse::list_series`, search arm: the only catalogue query combining the
    // FTS vector with a *mandatory* term. The three filtered variants guard theirs with
    // `$1::text IS NULL`, and still carry the `OR EXISTS` form this test would fail them for.
    let browse_search = find(&queries, "browse::list_series (search arm)", |q| {
        has_column(q, "cover_url")
            && q.sql.contains("plainto_tsquery")
            && !q.sql.contains("$1::text IS NULL")
    });

    for (label, query) in [
        ("matching::find_candidates", find_candidates),
        ("matching::find_candidates_multi", find_candidates_multi),
        ("admin_views::suggest_series_candidates", suggest_candidates),
        ("browse::list_series (search arm)", browse_search),
    ] {
        let plan = plan_of(&db.pool, query).await;
        assert_index_driven(&plan, label);
    }
}
